### ISSUE TITLE
Disaggregate costs on solution output

### ISSUE THREAD

**Issue by brynpickering** [calliope-project/calliope#46]
Currently the solution file provides the user with the costs associated with a technology as a lump sum. Pyomo offers outputs of fixed and variable costs, but this still doesn't give access to e.g. fuel costs, storage capacity costs, etc. 

To get the information, the constraint equations need to be applied in reverse to the results of the optimisation.

**Comment by brynpickering** [comment]
This may be better resolved by having a Solution sub-class for calliope, which is populated only after running a model, including the DataArray we currently have. That way we can have model.solution.get_costs(tech, loc, cost, cost_name) for getting disaggregated costs after running the model.

There is potentially too much confusion caused by trying to add another cost getter, when both 'get_cost' and 'get_costs' already exist. 

_Sent from my Xiaomi Redmi 3S using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by sjpfenninger** [comment]
0.6.0 now reports variable (time-varying) costs by default, but still not disaggregated by the different components.

**Comment by sjpfenninger** [comment]
Good enough functionality provided by 0.6.0
